export const SESSION_VALIDATION_COMPLETE = 'SESSION_VALIDATION_COMPLETE';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';

export const REQUEST_IS_BOOKING_ALLOWED_FOR_USER = 'REQUEST_IS_BOOKING_ALLOWED_FOR_USER';
export const RECEIVE_IS_BOOKING_ALLOWED_FOR_USER = 'RECEIVE_IS_BOOKING_ALLOWED_FOR_USER';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_AUTHENTICATED_INFO = 'RECEIVE_AUTHENTICATED_INFO';

export const REQUEST_FASTTRACK_NUMBERS = 'REQUEST_FASTTRACK_NUMBERS';
export const RECEIVE_FASTTRACK_NUMBERS = 'RECEIVE_FASTTRACK_NUMBERS';
export const SET_FASTTRACK_NUMBERS = 'SET_FASTTRACK_NUMBERS';

export const FETCH_NUMBERS = 'FETCH_NUMBERS';
export const REQUEST_NUMBERS = 'REQUEST_NUMBERS';
export const RECEIVE_NUMBERS = 'RECEIVE_NUMBERS';

export const TEMP_BOOK_NUMBERS = 'TEMP_BOOK_NUMBERS';
export const REQUEST_BOOK_NUMBERS = 'REQUEST_BOOK_NUMBERS';
export const RECEIVE_BOOK_NUMBERS = 'RECEIVE_BOOK_NUMBERS';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const REQUEST_TEMP_BOOK_NUMBERS_FROM_CACHE = "REQUEST_TEMP_BOOK_NUMBERS_FROM_CACHE";
export const RECEIVE_TEMP_BOOK_NUMBERS_FROM_CACHE = "RECEIVE_TEMP_BOOK_NUMBERS_FROM_CACHE";

export const REQUEST_USER_BOOK_NUMBERS = 'REQUEST_USER_BOOK_NUMBERS';
export const RECEIVE_USER_BOOK_NUMBERS = 'RECEIVE_USER_BOOK_NUMBERS';

export const REQUEST_LAST_EDITION_WINNING_NUMBER = "REQUEST_LAST_EDITION_WINNING_NUMBER";
export const RECEIVE_LAST_EDITION_WINNING_NUMBER = "RECEIVE_LAST_EDITION_WINNING_NUMBER";

export const REQUEST_PREV_WINNERS = "REQUEST_PREV_WINNERS";
export const RECEIVE_PREV_WINNERS = "RECEIVE_PREV_WINNERS";

export const REQUEST_NEXT_DRAW_DATE = "REQUEST_NEXT_DRAW_DATE";
export const RECEIVE_NEXT_DRAW_DATE = "RECEIVE_NEXT_DRAW_DATE";

export const REQUEST_CURRENT_EDITION = "REQUEST_CURRENT_EDITION";
export const RECEIVE_CURRENT_EDITION = "RECEIVE_CURRENT_EDITION";


